#!/bin/sh
# chkconfig: 345 97 03
# description:  This is a daemon for auto to connect iscsi

check_status() {
	pidfile='/var/run/backzfsmeta.pid'
	if [ ! -f $pidfile ]; then
		echo "surfsmeta is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "surfsmeta is  running, pid is $pid"
			exit 0
		else
			echo "surfsmeta is stopped, but pidfile at $pidfile is not cleaned. It may be caused by surfsmeta crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	#/lib/zstack/virtualenv/kvm/bin/activate && python -c "from kvmagent import kdaemon; kdaemon.main()" $@
        . /var/lib/zstack/virtualenv/zstack_surfs/bin/activate && python /var/lib/backzfsmeta/ideamon.py   $@
	#cd /var/lib/autoiscsi/ && python ideamon.py $@
fi

if [ $? -eq 0 ]; then
    echo "$@ surfsmeta ....  SUCCESS"
    exit 0
else
    echo "$@ surfsmeta .... FAILED"
    exit 1
fi
